apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: nginx-ingress-controller
spec:
  releaseName: nginx-ingress
  chart:
    spec:
      chart: nginx-ingress
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
        namespace: flux-system
      version: "1.4.1"
  interval: 15m
  timeout: 5m
  values:
    controller:
      metrics:
        enabled: true
      #podAnnotations:
      #  prometheus.io/scrape: "true"
      #  prometheus.io/port: "10254"
