apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: nginx-ingress-controller
spec:
  releaseName: nginx-ingress
  chart:
    spec:
      chart: nginx-ingress
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
        namespace: flux-system
      version: "1.4.1"
  interval: 5m
  timeout: 10m
  values:
    controller:
      metrics:
        enabled: true
      service:
        type:  NodePort
      image:
        ## The image repository of the Ingress Controller.
        repository: nginx/nginx-ingress
        tag: "3.7.1"
      volumes:
        - name: rdwr-kwaap
          configMap:
            name: rdwr-kwaap
      volumeMounts:
         - name: rdwr-kwaap
           mountPath: /etc/nginx/lua/plugins/rdwr-kwaap
           subPath: rdwr-kwaap
      config:
         entries: { allow-snippet-annotations: "true", plugins: rdwr-kwaap}

    ## The tag of the Ingress Controller image. If not specified the appVersion from Chart.yaml is used as a tag.
    # tag: "3.7.0"  
      #podAnnotations:
      #  prometheus.io/scrape: "true"
      #  prometheus.io/port: "10254"
